# Generated by Django 3.1.2 on 2020-10-16 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sight',
            name='Approaches',
            field=models.BooleanField(blank=True, help_text='Approaches', null=True),
        ),
        migrations.AlterField(
            model_name='sight',
            name='Chasing',
            field=models.BooleanField(blank=True, help_text='Chasing', null=True),
        ),
        migrations.AlterField(
            model_name='sight',
            name='Climbing',
            field=models.BooleanField(blank=True, help_text='Climbing', null=True),
        ),
        migrations.AlterField(
            model_name='sight',
            name='Eating',
            field=models.BooleanField(blank=True, help_text='Eating', null=True),
        ),
        migrations.AlterField(
            model_name='sight',
            name='Foraging',
            field=models.BooleanField(blank=True, help_text='Foraging', null=True),
        ),
        migrations.AlterField(
            model_name='sight',
            name='Indifferent',
            field=models.BooleanField(blank=True, help_text='Indifferent', null=True),
        ),
        migrations.AlterField(
            model_name='sight',
            name='Kuks',
            field=models.BooleanField(blank=True, help_text='Kuks', null=True),
        ),
        migrations.AlterField(
            model_name='sight',
            name='Moans',
            field=models.BooleanField(blank=True, help_text='Moans', null=True),
        ),
        migrations.AlterField(
            model_name='sight',
            name='Quaas',
            field=models.BooleanField(blank=True, help_text='Quaas', null=True),
        ),
        migrations.AlterField(
            model_name='sight',
            name='Running',
            field=models.BooleanField(blank=True, help_text='Running', null=True),
        ),
        migrations.AlterField(
            model_name='sight',
            name='Runs_From',
            field=models.BooleanField(blank=True, help_text='Runs_From', null=True),
        ),
        migrations.AlterField(
            model_name='sight',
            name='Tail_Flags',
            field=models.BooleanField(blank=True, help_text='Tail_Flags', null=True),
        ),
        migrations.AlterField(
            model_name='sight',
            name='Tail_Twitches',
            field=models.BooleanField(blank=True, help_text='Tail_Twitches', null=True),
        ),
    ]
